### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by sk33wiff** [au-research/ANDS-ResearchData-RIFCS-API#1]
I tried building it using ant, but I get the following error:

```
$ ant 
Buildfile: /tmp/ANDS-ResearchData-RIFCS-API/build.xml

build_jar:
    [javac] /tmp/ANDS-ResearchData-RIFCS-API/build.xml:32: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 63 source files to /tmp/ANDS-ResearchData-RIFCS-API/build/classes

BUILD FAILED
/tmp/ANDS-ResearchData-RIFCS-API/build.xml:32: /tmp/ANDS-ResearchData-RIFCS-API/lib does not exist.

Total time: 0 seconds
```

I can't find any information about its dependencies, neither a pom.xml or build.gradle file.

**Comment by rwalkerands** [comment]
Indeed, and we already fixed this (nine years ago) in the `develop` branch, but it seems I never merged the change into the `master` branch. I've done that now.

There are no external dependencies.

Please pull from the master branch and try again.
